### ISSUE TITLE
Install CLI command only has mac option

### ISSUE THREAD

**Issue by Psypher1** [sailhouse/docs#10]
n this page : https://docs.sailhouse.dev/getting-started/setup/

It shows install CLI command as 

```
brew install sailhouse/tap/sailhouse
```

and that's all. No options for other Operating Systems. Consider adding the commands for other OS

**Comment by estephinson** [comment]
Great raise - got a PR up now with a bunch of changes - including adding multi-OS instructions for installing the CLI.

**Comment by estephinson** [comment]
Closed as fixed in #11
