### ISSUE TITLE
SSL Cert Error

### ISSUE THREAD

**Issue by schererja** [sailhouse/docs#3]
Looks like I'm getting a NET::ERR_CERT_AUTHORITY_INVALID when trying to check out the docs.  Work computer won't even let me go farther than that.

**Comment by estephinson** [comment]
Thanks for the report, looking into it.

They're hosted on Netlify, which under the hood uses LetsEncrypt. I couldn't reproduce, but will try and dive deeper.

Can you access the [homepage](https://sailhouse.dev) at all?

**Comment by estephinson** [comment]
Cool beans, potentially. I'm double checking the SSL config with a couple of online tools but from what I can see it looks _okay_.

**Comment by schererja** [comment]
Sounds good, I think you should be fine to close this.  The work network is weird sometimes and "over" protective of stuff.  But at least you know if others having issues it most likely on their end.
